### ISSUE TITLE
Misc console.log & no dispatch on loopMode

### ISSUE THREAD

**Issue by lpshanley** [henriquehbr/svelte-typewriter#10]
See PR 
eb6246d91902f8002d02aacf6f1576314b90da6b

Removed console.log from the loopMode function and added a done event to be dispatched after each loop cycle to enable changing of dynamic typewriter content

**Comment by lpshanley** [comment]
I added a commit to fix an issue where loop mode never stops on component dismount.

**Comment by henriquehbr** [comment]
Thanks @lpshanley! released on [`v2.1.10`](https://github.com/henriquehbr/svelte-typewriter/releases/tag/v2.1.10)
