### ISSUE TITLE
"Delay" feature

### ISSUE THREAD

**Issue by Hejtmus** [henriquehbr/svelte-typewriter#11]
# Feature

Hello developers,

Once when I used svelte-typewriter for animating some text, animation was happening too early to be seen by user (if he doesn't look for it), so I got idea for feature. This feature will allow animation to be delayed by specified amount of time in milliseconds.
I hope my description is understandable, here is some example code.

# Example code

```
<Typewriter delay="500">
    <a on:click={toggleDomainVisibility}>
        {email.domain}
    </a>
</Typewriter>
```

BTW, amazing component, well written, I love it!

Best regards,
Filip Holcik.

**Comment by BerkinAKKAYA** [comment]
Hi! I implemented this feature in [this PR](https://github.com/henriquehbr/svelte-typewriter/pull/14).

**Comment by henriquehbr** [comment]
Hey there @Hejtmus!

Many thanks for using svelte-typewriter, i'm glad this library serves you well

This seems like a really nice feature to have, unfortunately i didn't had much time lately to work on it, but i'm really grateful @BerkinAKKAYA could land a PR with this and #5 

I will review the PR, make the required changes and merge it with `main` asap
