### ISSUE TITLE
Loop typewriter effect

### ISSUE THREAD

**Issue by henriquehbr** [henriquehbr/svelte-typewriter#3]
This option would be suited for displaying multiple texts on the same paragraph, similar to the gif below

![demo](https://cdn.crunchify.com/wp-content/uploads/2016/08/Crunchify-and-Typed-javascript-effect.gif)

The effect would be applied by passing the `loop` prop, and the children elements would alternate between a specific time interval (default is 3000 milliseconds) which can be changed by passing a `number` value to the `loop` prop representing the interval in milliseconds (`<Typewriter loop={5000} />`)

```html
<Typewriter loop>
    <p>This is a draft about the loop typewriter effect</p>
    <p>This is a draft about svelte-typewriter</p>
    <p>This text has nothing to do with the two previous phrases</p>
</Typewriter>
```

> **EDIT:** when using the `loop` prop, the tag name will be determined by the first child of the `<Typewriter>` component

**Comment by Taha-Firoz** [comment]
This isn't working in any of the repls, can anyone explain

**Comment by Taha-Firoz** [comment]
This comes up on your official repl console
![image](https://user-images.githubusercontent.com/42237761/90565234-0578e180-e1c0-11ea-94d2-b635169aa37a.png)

**Comment by Taha-Firoz** [comment]
What happened exactly?

**Comment by henriquehbr** [comment]
@Taha-Firoz sorry for the delay, this bug was caused due to a inconsistency introduced on the new 3.x API, the REPL demos were written with 2.x, i contacted npm in order to remove the last major bump version (3.0.0), as it introduced a lot of incompatibilites, and as i'm still getting used to implement semver on my projects, i forgot to release a alpha, beta or release candidate version previously, i'm sorry for this incovenient, this issue is already solved, npm removed the last version and the main REPL is now using the right version

**Comment by Taha-Firoz** [comment]
No it's fine but I think it might be a bug on my side, I'm using Firefox on windows 10 but the looping isn't working properly. It types out properly at first then gets stuck like this

![image](https://user-images.githubusercontent.com/42237761/90815373-0a669e00-e344-11ea-95d2-5bc609bc5fc0.png)
The cursor does continue to blink though.

This was the error on the repl console
![image](https://user-images.githubusercontent.com/42237761/90815462-308c3e00-e344-11ea-905f-cb120a6bfd02.png)


This was the error on the dev tools
![image](https://user-images.githubusercontent.com/42237761/90815437-266a3f80-e344-11ea-9deb-6ba4f6ece077.png)

**Comment by henriquehbr** [comment]
I wrote a note about this behavior on the loop mode on this [repl](https://svelte.dev/repl/e8b82d83f6c2444b97619238404bcd4d?version=3.24.1)

> Svelte REPL has a constraint that prevent loops for lasting longer than 100ms, This demo use small paragraphs in order to keep working a bit longer with the REPL limitation https://github.com/sveltejs/svelte-repl/issues/40
