### ISSUE TITLE
Maintenance-only mode

### ISSUE THREAD

**Issue by henriquehbr** [henriquehbr/svelte-typewriter#35]
After a whole year, a bunch of features, fixes and refactorings, i'm planning on making some final changes before putting the project on a maintenance-only mode, this means that i won't implement new features nor breaking changes on `svelte-typewriter`, only bug reports will keep being accepted

The main reason that leads to this decision, can be explained in the fact that this project is my first real open source experience, even though i commited countless errors messing around with npm, changelog generation and stuff alike, i learned a lot of valuable lessons about maintaining a package, but the most important of them is:

> **Avoid over-engineering at all costs**

For those who don't have a tight grasp on this concept, as stated on [this answer](https://stackoverflow.com/a/1941904/9182121) on StackOverflow, the term above refers to writing code that solves problems you don't have

At first, the main reason i wanted to start using Svelte was to make things simple and lightweight, and by impulsively adding things that are out of the scope of the project or not really necessary, they just end up being more future bugs or things to deal when refactoring, and besides that, i personally consider this project as finished, all the changes that i'll work towards before setting the project on a maintenance-only state can be found on [**this**](https://github.com/henriquehbr/svelte-typewriter/projects/4) project board

Thanks for all of you who contributed to the project, i'm really grateful for the actual state of  `svelte-typewriter` as a product of what we could achieve as a community, i'll keep working on many exciting open source projects in the future, stay tuned 😄

**Comment by evdama** [comment]
Please don't remove scramble mode. I use it inside the Nav on all of my pages so that would hit me hard if not available anymore. And also, it's working just fine as is so there's no bug.

**Comment by henriquehbr** [comment]
Good to hear that @evdama!

I'll undo the scramble mode removal, and take off the "BREAKING CHANGE" label, also, after i implement everything that has to be done, this issue will be left open without publishing a new version for some time in order to collect some feedback, so feel free to tell what would you like to be improved, fixed or removed from the project :)

If you don't mind, could you tell what version of `svelte-typewriter` you are using on your pages? so i can verify anything is broken on your, or any of the latest versions

**Comment by evdama** [comment]
Hi Henri! 😃  Thanks so much for keeping scramble mode!! 👍

I'm currently using 2.4.4 on my site which works just fine... as you remember there where 2 or so issues I found which I also reported and which got fixed like the `&` bug for example.

Other than that, I'll surely report anything odd I may find in the future as well of course but right now all seems working as expected and I'm basically using any of the available mode, from default, cascasde to scramble etc.

**Comment by henriquehbr** [comment]
The inconsistencies on scramble mode behavior began on version `2.4.5`, due to some major refactorings on the codebase (more details on #34), if you plan to use it on any of your applications, consider keeping on `2.4.4` and not upgrading while a fix is available, otherwise, everything is working fine and you are safe to go, almost all changes on this release were only refactorings, so you're not losing any new feature or bug fix

I will start working on it as soon as possible, a issue covering the whole process of re-adding and fixing anything wrong with scramble mode will be opened, if you wanna stay updated about the progress, keep an eye on it!

**Comment by BerkinAKKAYA** [comment]
Hi @evdama @henriquehbr,

I agree scramble feature is a bit off topic for this component. I forked this project and created a seperate [svelte-scramble package](https://github.com/BerkinAKKAYA/svelte-scramble) and published it in [npm](https://www.npmjs.com/package/svelte-scramble). I can maintain it if you won't re-implement it here.

**Comment by evdama** [comment]
> I agree scramble feature is a bit off topic for this component.

Maybe so in terms of how the code looks and also what it does. However, what got me thinking is that actually when it comes to using scramble or typewriter code in your app, the UI sections and places are exactly the same so it makes sense to have one package to do it all 😆

**Comment by henriquehbr** [comment]
Impressive @BerkinAKKAYA! not gonna lie, it's a good idea as well

Sorry for not being able to focus on this issue lately, i've been a bit busy, but also, still thinking about possible solutions for this, the first one that came in my head was to implement some kind of "plugin/addon system", really simple and straightforward and well-known and used on many projects

## The pros

Modularity at it's best, and as a consequence, smaller bundles/components, faster loading times and gives a single well defined responsibility for each `.svelte` component (instead trying to make some sort of "one man band")

## The cons

However, i'm not sure if it would actually be a good fit for `svelte-typewriter` because at first it seems a bit bulky for a small project purposes, i see it as being more suitable when you have a bunch of possibilities of plugins, like [Rollup](https://github.com/rollup/rollup) for instance

@evdama has a good point, and by coincidence, i think my suggestion can pretty much address this problem, as all plugins/addons might be contained on the same repository, or something like that, and they won't have as much of an impact as if they would if they were whole separated projects, also, that's the same reason that encourages the use of monorepos (avoid repetition), even though i don't think `svelte-typewriter` will grow that much, it's always good to have a future-proof architecture

If you guys can help on this one by sharing your points of view or ways to implement such behavior (other solutions are 100% welcome too) on this one, it would be hugely appreciated, as i'm can't manage to reach to a conclusion myself, besides that, it's always good to have other opinion about a same topic, in the end, three brains can think more than one :)

**Comment by evdama** [comment]
Hi Henry, doing a plugin system for a package this small is a bad idea imo... you'll spend more time working on that system rather than on typewriter itself. It's like chasing butterflies with nukes rather than a simple net 😄

Either keep it one package or split it, but even then, splitting means probably code deduplication and maintenance effort back and forth among the two packages...

I'd keep it as is, one package, and invest my time and effort at improving functionallity rather than going down the rabbit hole of plugin system and/or monorepo or split packages... It's just way to small of a package to justify the overhead and effort 🤓

**Comment by BerkinAKKAYA** [comment]
I also think plugin system might be overkill 😁 If you plan to add more modes, you may rename this project to something like `svelte-text-effects` and add a plugin system. Otherwise i think it's OK to just keep them in seperate packages.

**Comment by henriquehbr** [comment]
You've just read my mind @BerkinAKKAYA, i was also thinking on something like a "rebranding", i decided to get some inspiration from the huge and consolidated React library ecosystem (as most innovations come out there first)

After a bit of research, i discovered [`react-text-effects`](https://github.com/rcdexta/react-text-effects), which does exactly what the title suggests, i think we can transform this project on pretty much something like that, including the plugin support part

Their docs can be found [here](https://react-text-effects.surge.sh) (which by the way, seemed really simple and aestetically pleasing at the same time, i'm planning to make something like that for `svelte-typewriter`)

What is the gentleman's veredict?

**Comment by BerkinAKKAYA** [comment]
I didn't know about `react-text-effects` 😁 I just checked and your typewriter effect looks better in my opinion.

I don't know why there is a need for components in the `react-text-effects`. You can do most of them with only one or two lines of CSS using `transition`.

I actually can't think of any effects that would worth changing the whole structure of this component. I personally love the simplicity of this project. It does one thing and does it good 😁 If you find more modes like typewriter and scramble, it would probably worth turning it to a collection, though. It's up to you to decide.

Good luck!

**Comment by evdama** [comment]
I second that... it's brilliant the way it is, with typewriter & scamble... adding more? why not... but I'd not spend time on adding bloat like a plugin system and whatnot.

**Comment by henriquehbr** [comment]
Indeed, thanks for the valuable feedback, i agree that it's really unnecessary to include a whole Svelte component for what can be done with css one-liners, i'll keep it as-is, focused on what it already does and start working on fixing the scramble mode asap

Again, my apologies for the delay, i couldn't find some time to get things working on the last weeks

**Comment by evdama** [comment]
> Again, my apologies for the delay, i couldn't find some time to get things working on the last weeks

If anything then we have to thank you for this awesome package, and who knows, maybe there'll be more cool ideas for things to add in the future... 🙌 😋

Doing a rename from typewriter to `text-effects`... why not, if, over time, `typewriter` collects more things like scamble mode, then I don't see an issue with that either because it's then justified and for anybody using the package a simple search and replace 😆

**Comment by henriquehbr** [comment]
I'm transferring this issue to a [project board](https://github.com/henriquehbr/svelte-typewriter/projects/4) in order to keep things organized and help keep track of pending tasks instead of doing that on this issue description, commits made can still be tracked from here

**Comment by henriquehbr** [comment]
The reason for so many frequent changes recently (especially on this "final" development stage), like going from Rollup to esbuild, then planning to change again to Snowpack, and also rewriting the project in TypeScript, and cogitating going back to vanilla JS, is that as the project has been stale for a little more than a month (which i focused to study more and sharpen my knowledge) i've learned some new interesting stuff that i would like to immediately apply on `svelte-typewriter`, which in turn can cause some conflicts with the library itself and the way it's structured as a consequence of such quick change , but those are long-term benefits that will greatly improve the DX (developer experience of the project, besides making everything way simpler and less cluttered (let's face it, some things are really messy and need to be improved before considering this as done)

**Comment by evdama** [comment]
Hi Henry, curious aobut the plans 😄  Are you now planing on relasing a 2.46 with scamble mode readded at some point or keep things at 2.45 with 2.44 working with scramble mode (which is what I'm currently using)?

**Comment by henriquehbr** [comment]
What's up @evdama!

I'm glad you're interested in the upcoming updates, just to make things clear, lately i've been kinda stagnated in open source in general and couldn't get things done (as can be seen on my contribution board), due to being busy working on a "revamp" on my current work setup

I'm migrating from Windows 10, which i used for gaming only, but it's a real pain for daily development which was only hindering my productivity (shame on me) to [Arch Linux](http://archlinux.org/), as soon as i get things done (which shouldn't take long from now on) i'll immediately hop back on `svelte-typewriter` at full productivity :)

If you're interested, i'm thinkering with some [dotfiles](https://github.com/henriquehbr/dotfiles) that i'll be using on the long-run of my soon-to-be daily system, and even an fully automated install script with personal configs

**Comment by henriquehbr** [comment]
Oops, forgot to answer your question on the previous comment 😬 

Yes, the scramble mode is going to be fixed on `2.4.6`

**Comment by evdama** [comment]
> Oops, forgot to answer your question on the previous comment 😬

😉 


> Yes, the scramble mode is going to be fixed on `2.4.6`
Excellent 👍

**Comment by henriquehbr** [comment]
As the project being migrated to sourcehut, i'll be closing this issue, also because i consider this project as feature-complete, so from now on i'll be finally moving the project to maintenance-mode, if you have any bugs to report, feel free to open a ticket [here](https://todo.sr.ht/~henriquehbr/svelte-typewriter)
