### ISSUE TITLE
Re-add scramble mode

### ISSUE THREAD

**Issue by henriquehbr** [henriquehbr/svelte-typewriter#37]
> Part of the maintenance mode [roadmap](https://github.com/henriquehbr/svelte-typewriter/projects/4) (#35)

The scramble mode (previously removed on #36), will be re-added to the project, as recent requests on maintenance-mode thread

As the last set of changes part of the maintenance mode plan still wasn't released as a new version, this can be considered as a non-breaking change

**Comment by evdama** [comment]
Hi Henry :wave:
I think this issue can be closed no? I'm currently using 2.4.4 where scramble mode still works as opposed to 2.4.5...
Any ETA on 2.4.6 that will have it working again, including all other changes you've planned?

**Comment by henriquehbr** [comment]
Hey @evdama!

I don't think so, even though the last version 2.4.4 is still working properly, version 2.4.5 actually has some problems when it comes to the scramble mode, and taking into consideration that it has a considerable amount of downloads and it's published on npm for quite some time, it simply cannot be unpublished

i'm focusing on other projects lately, even though i really love this project and want to contribute to it, i simply don't have the time for it as before

But, if you're willing to, i can add you as a contributor, so you can make direct changes to the repo, there are some PR's open, most of them are really cool features that would fit nicely in the project scope, and besides that, it would be really great to have someone else on board of the project 😄

**Comment by evdama** [comment]
Well, as long as it work (scamble mode)...
I've got the same limitation... time that is... 🤷 
Maybe someone else can take you up on the offer? 😄

**Comment by henriquehbr** [comment]
Hey @evdama, took longer than i wanted, but it's finnaly here, the scramble mode has been re-introduced on version [3.0.0-alpha.0](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha0---2021-11-05), if you could test it and check if everything is running smoothly, please? let me know, and we shall close this issue

**Comment by evdama** [comment]
upgraded to `3.0.0-alpha.1` and scramble mode is working 👍 
thank you so much!!!! :)
