### ISSUE TITLE
[enhancement] Specify the container element

### ISSUE THREAD

**Issue by fabianmossberg** [henriquehbr/svelte-typewriter#43]
It would be great if it was possible to define the wrapping element of the typewriter:

```svelte
<Typewriter el="h1">
  <span>Testing the typewriter effect</span>
  <span>The typewriter effect cascades by default</span>
  <span>Lorem ipsum dolor sit amet consectetur</span>
</Typewriter>
```

Would result in:

```html
<h1>
  <span>Testing the typewriter effect</span>
  <span>The typewriter effect cascades by default</span>
  <span>Lorem ipsum dolor sit amet consectetur</span>
</h1>
```

**Comment by henriquehbr** [comment]
@fabianmossberg Thanks to the recent release of Svelte 3.47.0, this now can be done with [`<svelte:element>`](https://svelte.dev/docs#template-syntax-svelte-element), i've implemented this funcionality through a `element` prop, this new feature is now available from version [3.0.0-alpha.14](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha14---2022-06-29) onwards, feel free to close this issue if this new version covers your use-case
