### ISSUE TITLE
[feature] ignoring functionality

### ISSUE THREAD

**Issue by haudraufhaun** [henriquehbr/svelte-typewriter#49]
I just wanted to ask if there is a feature that helps me to ignore elements inside my typewriter component.

**Comment by henriquehbr** [comment]
At the moment, such feature is not present on `svelte-typewriter`, but by coincidence, @fabianmossberg suggested exactly this on https://github.com/henriquehbr/svelte-typewriter/issues/41#issuecomment-790706820, i'm planning towards implementing it on the project once i finish some other tasks that are pending for quite some time

You can check it's status on the [Features board](https://github.com/henriquehbr/svelte-typewriter/projects/2)

**Comment by HAUDRAUFHAUN** [comment]
Ok, thank you very much @henriquehbr

**Comment by henriquehbr** [comment]
@haudraufhaun Released on version [3.0.0-alpha.2](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha2---2021-11-06)
