### ISSUE TITLE
[Feature Request] Add backspace animation

### ISSUE THREAD

**Issue by AshamedConsequence** [henriquehbr/svelte-typewriter#50]
Would it be possible to add a backspace option, where during the animation, it backtracks n times before continuing the animation?

An example of what that would look like would be 
```svelte
<Typewriter>
    <p>
        This is some texit with
        <Backspace count={7}/>
         t with an intentional spelling mistakes.
    </p>
</Typewriter>
```

**Comment by henriquehbr** [comment]
Thanks for your suggestion!

I'm afraid i couldn't fully understand how this would work in practice, should the first 7 characters of the line right after the `<Backspace>`  component (as pointed by the `count` property) be backspaced and retyped during the animation?

**Comment by AshamedConsequence** [comment]
That's my bad, I should've included what it would look like.

This would be a 3 phase animation.

Phase one would animate the text to write out:
`This is some texit with`

Phase two would animate the backspace counting back:
`This is some tex`

Phase three would animate the rest of the typing:
`This is some text with an intentional spelling mistakes.`

Of course, the structure of this feature isn't really set in stone. It's just resembles the way that [react-typist](https://github.com/jstejada/react-typist/blob/master/README.md#Typist.Backspace) implements its backspace.

**Comment by henriquehbr** [comment]
Got it, thanks for the explanation, i will also take a look at react-typist source code to see how things are done there, in order to achieve the optimal way of implementing such feature

Expect to see this feature shipped on the next week or so, unfortunately, at the moment i couldn't dedicate much time for this project

**Comment by AshamedConsequence** [comment]
That's awesome man. Thanks.

**Comment by henriquehbr** [comment]
@AshamedConsequence Firstly, i would like to apologize for the delay, i haven't gotten enough time to dedicate to this project as it deserves

After tinkering a bit with your idea, i came to the conclusion that such addition would have a rather complex implementation, besides that, this is something that can be already done with the features that are currently available, see the example below:

```svelte
<style>
    /* keep the typewriter child elements on a single line */
    :global(.typewriter-container) {
        display: inline-flex;
    }
</style>

<Typewriter mode="loop">
    <!-- this element won't be affected by the animation -->
    <span data-static>This is some tex</span>
    <span>it with</span>
    <span>t with intentional spelling mistakes</span>
</Typewriter>
```

I've tested it locally and this reproduces the 3 phase animation you mentioned above, let me know if this works for your use case

**Comment by henriquehbr** [comment]
As the project is migrating to sourcehut, i'll be closing this issue, if you feel that the reported problem haven't been solved, feel free to reopen it [here](https://todo.sr.ht/~henriquehbr/svelte-typewriter), otherwise, you can just ignore this message
