### ISSUE TITLE
Uncaught (in promise) TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by evdama** [henriquehbr/svelte-typewriter#57]
I'm on version 2.4.4 because I need scramble mode. With this version I'm getting following error which the screenshot shows
![Screen Shot 2021-08-01 at 10 23 35](https://user-images.githubusercontent.com/39374084/127764525-a33b3849-3c69-4242-8fa2-af175ea9735b.png)

Using dev tools and clicking into it I get to this snippet of code from `default.js` where the line `const { currentNode: lastElementToFinish } = elements.reduce((longestTextElement, element) => {` seems to be where the error occurs...

```js
	// Modularize this
	const { currentNode: lastElementToFinish } = elements.reduce((longestTextElement, element) => {
		const longestTextLength = longestTextElement.text.length
		return element.text.length > longestTextLength
			? (longestTextElement = element)
			: longestTextElement
	})
```

So it seems that `elements` needs an empty check before the reduce...

**Comment by henriquehbr** [comment]
Can you check if this is still happening on [`3.0.0-0`](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha0---2021-11-05)?

**Comment by evdama** [comment]
Hi Henry, just upgraded to `3.0.0-alpha.1` and on first glance everything seems to work 🥳 
I'll have a closer look on Monday 👍 
Thanks a ton!!!!

**Comment by evdama** [comment]
getting on error in the console thoug
![Screen Shot 2021-11-06 at 17 00 32](https://user-images.githubusercontent.com/39374084/140615935-efffe890-3626-41c6-aef6-b5e543d62240.png)
h

**Comment by henriquehbr** [comment]
That's odd, can you share a snippet of code of the component you're using to perform the animation, please?

**Comment by evdama** [comment]
It somehow has to do with this line https://github.com/henriquehbr/svelte-typewriter/blob/b0516aba6c0f3b97c99e22efd7c9243f654730c6/src/helpers/getLongestTextElement.js#L8 and the fact that  it's only being triggered once inside a block of code where the user is authenticated.

**Comment by henriquehbr** [comment]
Can you provide a environment where i can reproduce this issue, please? this would really help me narrow down the root cause of this problem

Feel free to share whatever is better or more accessible to you, be it the link to a repo or a REPL

**Comment by henriquehbr** [comment]
@evdama Is this problem still present on the latest version?
