### ISSUE TITLE
Issue : [!] (plugin svelte) ParseError: Expected if, each or await

### ISSUE THREAD

**Issue by AlphaLaser** [henriquehbr/svelte-typewriter#60]
I was using the svelte Typewriter in for my website.

Here is the full error I'm getting : 

```[!] (plugin svelte) ParseError: Expected if, each or await
node_modules\svelte-typewriter\lib\Typewriter.svelte
67: /*# sourceMappingURL=node_modules/svelte-typewriter/lib/Typewriter.svelte.map */</style>  
68:
69: {#key reinit}
      ^
70:   <div
71:     use:typewriter={options}
ParseError: Expected if, each or await
    at error (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\parse\index.ts:93:3)
    at mustache (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\parse\state\mustache.ts:225:11)
    at new Parser$1 (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\parse\index.ts:45:12)
    at parse (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\parse\index.ts:208:17)                                                                                ror.ts:25:16)
    at compile (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\svelte\src\compiler\compil\parse\index.ts:93:3)e\index.ts:79:14)                                                                             \state\mustache.ts:225:11)
    at C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\rollup-plugin-svelte\index.js:252:2arse\index.ts:45:12)2                                                                                             dex.ts:208:17)
    at ModuleLoader.addModuleSource (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\rollue\index.ts:79:14)p\dist\shared\rollup.js:17808:30)                                                             2
    at ModuleLoader.fetchModule (C:\Users\Adit\Desktop\Portfolio-svelte\node_modules\rollup\dip\dist\shared\rollup.js:17808:30)st\shared\rollup.js:17862:9)                                                                  st\shared\rollup.js:17862:9)
    at async Promise.all (index 2)
```

**Comment by henriquehbr** [comment]
Hi @AlphaLaser!

If i recall correclty, the `{#key}` block was introduced recently in one of the newer versions of Svelte, so i'm almost sure such error is being caused by an outdated version of Svelte, which version are you using?

**Comment by AlphaLaser** [comment]
Hey

I'm using Svelte 3.44.1
![image](https://user-images.githubusercontent.com/59497243/140574106-4cc7bf86-7cd0-4276-a837-40a1c9944dee.png)

**Comment by AlphaLaser** [comment]
@henriquehbr 
Another thing that may be helpful is that I wanted to use Bulma with svelte. So I was using this template.

https://github.com/manuel3108/svelte-bulma-template

**Comment by henriquehbr** [comment]
Tried reproducing locally with the bulma template, and the version returned by npm view svelte version didn't match with the one listed on package.json, can you share the svelte version on your package.json?

**Comment by AlphaLaser** [comment]
ohhhhh, my version is 3.0.0 I think (I'm new to this node environment). I'm mostly an ml guy haha

```{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^12.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "autoprefixer": "^9.8.8",
    "node-sass": "^6.0.1",
    "postcss": "^7.0.39",
    "rollup": "^2.3.4",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^5.1.2",
    "svelte": "^3.0.0",
    "svelte-preprocess": "^4.9.8"
  },
  "dependencies": {
    "bulma": "^0.9.0",
    "sass": "^1.26.10",
    "sirv-cli": "^0.4.4"
  }
}
```

How do I upgrade it ?

**Comment by henriquehbr** [comment]
I just checked Svelte changelog, and the `{#key}` block was only introduced on version [3.28.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3280), so indeed, that's actually my fault for not specifying `svelte` as a [`peerDependency`](https://flaviocopes.com/npm-peer-dependencies/)

I'll set it to `>=3.28.x` to ensure that the `{#key}` block (and any other features) are supported by the `svelte` version installed alongside `svelte-typewriter`

**Comment by AlphaLaser** [comment]
Aaah got it, Any idea how I can manually upgrade my svelte version rn to get it to work ?

**Comment by henriquehbr** [comment]
You can either:

- Manually change it on the `package.json` for one of the existing versions (you can check them on the "Versions" tab on [npm](https://npmjs.com))
- Or use a nice little tool known as [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) for automatically updating all of your dependencies to the latest version

> I'm not sure if npm currently has some way to easily update your dependencies on `package.json`, if so, `npm-check-updates` is not needed, it's just a old habit i developed from a long time ago where there was no way to easily update your dependencies

**Comment by henriquehbr** [comment]
Just released a new version ([3.0.0-alpha.1](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha1---2021-11-05)) that fixes this issue, can you check if it's working now, please?

**Comment by AlphaLaser** [comment]
Sure

**Comment by AlphaLaser** [comment]
Hey !

Actually I tried integrating the Svelte typewriter but I was getting loads of errors.

I'm very new to svelte. So I'm not sure If i'm doing something wrong.

Can you try adding the feature to see what's wrong?

Link to Github - https://github.com/AlphaLaser/Portfolio

Link to Deployment -  https://aditmagotra.netlify.app/

I want t add the typewriter just below the social icons

**Comment by henriquehbr** [comment]
@AlphaLaser i just opened a PR at your Portfolio repo with some changes that might help you with your problem

**Comment by AlphaLaser** [comment]
Hey,


It was not deploying initially but I fixed that by changing the `scripts` in my `package.json` from

```
"scripts": {
    "dev": "vite"
  },

```
to

```
"scripts": {
    "dev": "vite",
    "build": "vite build"
  },
```

because netlify is deploying using `npm run build`.

But, it is showing 2 errors while deployment.
```

9:37:11 PM:      [vite]: Rollup failed to resolve import "/build/bundle.css" from "index.html".
9:37:11 PM:      This is most likely unintended because it can break your application at runtime.
9:37:11 PM:      If you do want to externalize this module explicitly add it to
9:37:11 PM:      `build.rollupOptions.external`
9:37:11 PM:      error during build:
9:37:11 PM:      Error: [vite]: Rollup failed to resolve import "/build/bundle.css" from "index.html".
9:37:11 PM:      This is most likely unintended because it can break your application at runtime.
9:37:11 PM:      If you do want to externalize this module explicitly add it to
9:37:11 PM:      `build.rollupOptions.external`
9:37:11 PM:      at onRollupWarning (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43253:19)
9:37:11 PM:      at onwarn (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43037:13)
9:37:11 PM:      at Object.onwarn (/opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22994:13)
9:37:11 PM:      at ModuleLoader.handleResolveId (/opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22338:26)
9:37:11 PM:      at /opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22310:26


```

**Comment by henriquehbr** [comment]
Probably as this message says:

```
9:37:11 PM:      [vite]: Rollup failed to resolve import "/build/bundle.css" from "index.html".
```

You're trying to import a non-existent css stylesheet from `build/bundle.css` on your `index.html` (previously generated by rollup), i'm not sure, but i would try changing that to something like `./src/main.scss` (yes, you can safely do that with Vite, it gets re-mapped to the output css file on build)

**Comment by AlphaLaser** [comment]
I tried `./src/main.scss`, `/src/main.scss`, and `src/main.scss`

Nothing's working :(

**Comment by henriquehbr** [comment]
After changing the stylesheet path, are you still getting the same error message?

**Comment by AlphaLaser** [comment]
It's something really weird now. The deployment shows absolutely no errors and a successful deployment but when I open the deployment link, this happens

<center>
<p>
<img src = "https://user-images.githubusercontent.com/59497243/141891016-259fd442-92ca-4a23-b57c-80131e81c90e.png"></p>
</center>

**Comment by AlphaLaser** [comment]
Wait no

I fixed that error. (index.html directory was set wrongly)

When I use `./src/main.scss`, I'm getting a blank page.

But when I use `src/main.scss`, I'm getting the same error.

```
9:27:40 AM:      [vite]: Rollup failed to resolve import "src/main.scss" from "index.html".
9:27:40 AM:      This is most likely unintended because it can break your application at runtime.
9:27:40 AM:      If you do want to externalize this module explicitly add it to
9:27:40 AM:      `build.rollupOptions.external`
9:27:40 AM:      error during build:
9:27:40 AM:      Error: [vite]: Rollup failed to resolve import "src/main.scss" from "index.html".
9:27:40 AM:      This is most likely unintended because it can break your application at runtime.
9:27:40 AM:      If you do want to externalize this module explicitly add it to
9:27:40 AM:      `build.rollupOptions.external`
9:27:40 AM:      at onRollupWarning (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43253:19)
9:27:40 AM:      at onwarn (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43037:13)
9:27:40 AM:      at Object.onwarn (/opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22994:13)
9:27:40 AM:      at ModuleLoader.handleResolveId (/opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22338:26)
9:27:40 AM:      at /opt/build/repo/node_modules/rollup/dist/shared/rollup.js:22310:26
```

**Comment by henriquehbr** [comment]
I tested your portfolio locally with `/src/main.scss` on `index.html` and it worked fine for me, no problems at all on build or when running `vite preview`, i even tried previewing the `dist` directory content with [`http-server`](https://github.com/http-party/http-server) and it loaded without any errors as well

In situations like this (getting a blank page), consider checking your console for make sure there aren't any errors preventing the page from loading

**Comment by AlphaLaser** [comment]
Hey man, thanks a lot for helping me out.

Really sorry I couldn't reply as my exams were going on :(

**Comment by AlphaLaser** [comment]
I fixed the issue !

It's deployed at https://aditmagotra-portfolio.netlify.app/ now !

Thanks a lot again !
