### ISSUE TITLE
.env environment variable replacement not working

### ISSUE THREAD

**Issue by evdama** [henriquehbr/svelte-typewriter#74]
In a sveltekit app I have a `.env` file with environment variables such as `VITE_GOLIVE_DATE = 'July 2026'` which I'd like to use like so 
```svelte
        <Typewriter loop}>
          <div>foo</div>
          <div>bar</div>
          <div>under construction until {import.meta.env.VITE_GOLIVE_DATE}</div>
        </Typewriter>
```
but instead of showing me
```
foo
bar
under construction until July 2026
```
I just get the first two divs i.e. after `bar` it starts over with `foo` again and so forth...
```
foo
bar
```

**Comment by henriquehbr** [comment]
Would you mind sharing a branch or repository for me to reproduce this issue? this way is better for me to test some possible solutions and have a better understanding on the context of your issue

**Comment by evdama** [comment]
It's litterally just a bare svk app I just started about an hour ago, created a `.env` file with above content `VITE_GOLIVE_DATE = 'July 2026'`, installed `svelte-typewriter` as a dev dependency and then put
```svelte
        <Typewriter loop}>
          <div>foo</div>
          <div>bar</div>
          <div>under construction until {import.meta.env.VITE_GOLIVE_DATE}</div>
        </Typewriter>
```
inside `src/routes/index.svelte` and started the dev server using `npm run dev`.

**Comment by henriquehbr** [comment]
I tried a few solutions from what i could find through official documentation, GitHub issues and StackOverflow answers, but unfortunately, none of them worked

I'll return with an answer as soon as possible, but expect it to take a while as i'm not that familiar with SvelteKit

**Comment by henriquehbr** [comment]
@evdama I'm not sure if you already tried it, but there's a [section](https://kit.svelte.dev/faq#env-vars) regarding environment variables on SvelteKit FAQ, probably it might be of some help

**Comment by evdama** [comment]
actually, forget about the `.env` and vite config for the moment... I tried to make it simpler by doing this
```svelte
<script>
let foo = "mouse"
</script>

        <Typewriter loop}>
          <div>foo</div>
          <div>bar</div>
          <div>under construction until {foo}</div>
        </Typewriter>
```

**Comment by henriquehbr** [comment]
I think it has something to do with the fact that the `<Typewriter>` component is not compatible with the SSR model of SvelteKit, i've reached this conclusion after fiddling around for a solution and got this error message:

> `<Typewriter>` is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

The message above led me to [this](https://github.com/carbon-design-system/carbon-components-svelte/issues/595#issuecomment-818308275) comment on a issue opened on the `carbon-components-svelte` repository

I'm not 100% sure, but from my understanding, i think it means that vite must process `svelte-typewriter` first instead of letting SvelteKit just import it right away, but even following the workaround proposed on the comment i linked on the paragraph above wasn't enough to make it work for me

**Comment by henriquehbr** [comment]
Almost forgot to include an important detail, in order to get the error message above, i followed the steps from [this](https://github.com/sveltejs/kit/issues/905#issuecomment-863605244) comment on a issue opened on the SvelteKit repo

**Comment by evdama** [comment]
hm... ok... I see... not sure either, I'll have another try at this over the next few days 🤷

**Comment by henriquehbr** [comment]
Hey @evdama! sorry for the delay, but i've just tested the latest version `svelte-typewriter` on a bare SvelteKit template, and it worked just fine for me, all animation modes and options (including the use of environment variables), can you confirm if it's also working for you, please?

**Comment by evdama** [comment]
3.0.0-beta.1 broke it again whereas 3.0.0-alpha.11 works

In this example, all divs start at the same time i.e. foo, bar and baz start at the same time rather than one after the other.

```
        <Typewriter loop delay={ 5000 } interval={ 60 } }>
          <div>foo...</div>
          <div>bar...</div>
          <div>baz...</div>
        </Typewriter>
```

**Comment by henriquehbr** [comment]
Starting from [3.0.0-alpha.13](https://git.sr.ht/~henriquehbr/svelte-typewriter/tree/main/item/CHANGELOG.md#300-alpha13---2022-06-29), mode props are no longer a thing, you must pass the animation mode as a string to the `mode` prop, examples below:

```svelte
<Typewriter mode="loop" delay={5000} interval={60}>
    <div>foo...</div>
    <div>bar...</div>
    <div>baz...</div>
</Typewriter>
```

```svelte
<Typewriter mode="scramble" delay={2000} interval={80}>
    <span class="text-lg">The Ocean</span><span class="text-sm">is big</span>
</Typewriter>
```

I've tested both of your examples above on the latest version, making the proper adaptations, and they worked just fine for me, feel free to close this issue if the solution above solves your problem

**Comment by henriquehbr** [comment]
As the project is migrating to sourcehut, i'll be closing this issue, if you feel that the reported problem haven't been solved, feel free to reopen it [here](https://todo.sr.ht/~henriquehbr/svelte-typewriter), otherwise, you can just ignore this message
