### ISSUE TITLE
[Feature request] Add an option to delay the start of unwrite effect in loop effect.

### ISSUE THREAD

**Issue by Sonlis** [henriquehbr/svelte-typewriter#76]
Currently, it is only possible to delay the time between each letter removal, but the Unwrite effect always starts very quickly once the component is written and and is impossible to delay. I think having a prop like `unwriteDelay` to delay the unwriting effect start would be very appreciated.

**Comment by henriquehbr** [comment]
You can do that by passing a number to the `loop` prop, this number being the interval (in milliseconds) between each word, example below:

```svelte
<Typewriter loop={3000}>
    <p>Hello</p>
    <span>World!</span>
</Typewriter>
```

Can you confirm if that works for you?

**Comment by Sonlis** [comment]
Indeed, it is exactly what I was looking for, thanks!
