### ISSUE TITLE
Would it be possible to add a "disabled" mode?

### ISSUE THREAD

**Issue by alexbjorlig** [henriquehbr/svelte-typewriter#77]
I'm currently implementing visual e2e tests using [Percy](https://percy.io/).

However when comparing screenshots of the DOM, it would be nice to disable svelte-typewriter.

Let me know if this is possible.

**Comment by henriquehbr** [comment]
Correct me if i'm wrong, as i'm not very familiar with such tool, but from what i've found on it's [documentation](https://docs.percy.io/docs/environment-variables), you have access to some environment variables like `$PERCY_ENABLE` which can be useful in cases where you need to conditionally render `<Typewripter>`

**Comment by henriquehbr** [comment]
Sorry for the delay @alexbjorlig, i've implemented a `disabled` prop that allows you to do just that, it's currently available from version [3.0.0-alpha.13](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha13---2022-06-29) onwards, feel free to close this issue if you feel that this new features addresses your needs

Be aware that this latest version brings some breaking changes involving the way you select different animation modes on the `<Typewriter>` component, the documentation has been carefully reviewed and updated with the new changes, and it should have everything you need when migrating to this new version

There's also a new interactive demo application where you can test this and many features from, in case you wanna check it out: https://henriquehbr.github.io/svelte-typewriter
