### ISSUE TITLE
[Feature Request] setting for thinner cursor

### ISSUE THREAD

**Issue by 151henry151** [henriquehbr/svelte-typewriter#78]
Would love to be able to set the width of the cursor, to have a 1px width "line-type" cursor instead of the "block cursor."

**Comment by henriquehbr** [comment]
I've just implemented this on version [3.0.0-alpha.12](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha12---2022-06-21), it's already published on npm, please, let me know if it works for you, and feel free to close this issue if you feel that this problem has been solved

**Comment by 151henry151** [comment]
Thank you!
