### ISSUE TITLE
Unknown file extension ".svelte"

### ISSUE THREAD

**Issue by alexbjorlig** [henriquehbr/svelte-typewriter#83]
After upgrading sveltekit to latest version, we are starting to get the following error message:

```
Unknown file extension ".svelte" for <path-to-project>/node_modules/svelte-typewriter/src/Typewriter.svelte
```

Is this something you have seen before?

**Comment by henriquehbr** [comment]
Can you provide some context of the code where this problem is happening? a snippet or a repo URL would be really useful to help me reproduce this issue

**Comment by alexbjorlig** [comment]
Sorry @henriquehbr  - I should have done that. Let me work on that

**Comment by alexbjorlig** [comment]
It turns out it was a mono-repo issue. Adding the dependency explicitly to the package using it removed the warning. Sorry for disturbing you. Just read your readme about moving away from Github - made me think 😅 Do you have "other arguments" than Copilot or do you feel like that is important enough in itself?

**Comment by henriquehbr** [comment]
@alexbjorlig the copilot controversy was an important factor that contributed to my sourcehut migration, but it goes beyond that, as a platform, sourcehut is much more aligned with my vision and values of software development than GitHub, it's open-source, lightweight, free of trackers and data harversting, gives the possibility of self-hosting, and the most importantly, not owned by some evil company

I want to make this change roll out as smoothly as possible, the project will still be maintained as normally (it will also stay on npm), currently there's already a repo for [svelte-typewriter](https://sr.ht/~henriquehbr/svelte-typewriter/) there, with a issue tracker on the "tickets" tab, that works just like GitHub issues

**Comment by alexbjorlig** [comment]
Ok - sounds like a great plan. I will read more about sourcehut. I don't agree on the narrative that Microsoft is evil - but it's your project. And a really cool project - you rock 😎
